### ISSUE TITLE
How to find the map file? How do I start my first operation?

### ISSUE THREAD

**Issue by 4C4247** [Nalzy64/DbD-MiniMap#1]
How to configure exe

**Comment by tenshi64** [comment]
Search in Google: DbD callout maps, download what you need, import all files, choose what map you would like to display with the app, and press the button to display it. Use the latest version to make sure everything works correctly.

**Comment by 4C4247** [comment]
> Search in Google: DbD callout maps, download what you need, import all files, choose what map you would like to display with the app, and press the button to display it. Use the latest version to make sure everything works correctly.

thx u~I got it.appriciate！

**Comment by tenshi64** [comment]
Great. Enjoy the app.
